language: swift
xcode_project: LazyTransitions.xcodeproj
xcode_scheme: LazyTransitions
osx_image: xcode7
script:
  - xcodebuild -scheme LazyTransitions -workspace LazyTransitions.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'LazyTransitions'
